export const mockProducts = [
  { id: 1, name: 'Clássico da Casa', price: 24.90, availability: 1, category: 'Hambúrgueres', imageUrl: '/images/categories/burguer.jpg' },
  { id: 2, name: 'Bacon Supreme', price: 29.90, availability: 1, category: 'Hambúrgueres', imageUrl: '/images/categories/burguer.jpg' },
  { id: 3, name: 'Cheddar Melt', price: 27.90, availability: 1, category: 'Hambúrgueres', imageUrl: '/images/categories/burguer.jpg' },
  { id: 4, name: 'Duplo Smash', price: 31.90, availability: 1, category: 'Hambúrgueres', imageUrl: '/images/categories/burguer.jpg' },
  { id: 5, name: 'Veggie Burger', price: 26.90, availability: 1, category: 'Hambúrgueres', imageUrl: '/images/categories/burguer.jpg' },
  { id: 6, name: 'Mussarela', price: 39.90, availability: 1, category: 'Pizza', imageUrl: '/images/categories/pizza.jpg' },
  { id: 7, name: 'Calabresa', price: 44.90, availability: 1, category: 'Pizza', imageUrl: '/images/categories/pizza.jpg' },
  { id: 8, name: 'Frango com Catupiry', price: 47.90, availability: 1, category: 'Pizza', imageUrl: '/images/categories/pizza.jpg' },
  { id: 9, name: 'Quatro Queijos', price: 49.90, availability: 1, category: 'Pizza', imageUrl: '/images/categories/pizza.jpg' },
  { id: 10, name: 'Do Chef', price: 52.90, availability: 1, category: 'Pizza', imageUrl: '/images/categories/pizza.jpg' },
  { id: 11, name: 'Carne', price: 9.00, availability: 1, category: 'Pastel', imageUrl: '/images/categories/pastel.jpg' },
  { id: 12, name: 'Queijo', price: 9.00, availability: 1, category: 'Pastel', imageUrl: '/images/categories/pastel.jpg' },
  { id: 13, name: 'Pizza', price: 10.00, availability: 1, category: 'Pastel', imageUrl: '/images/categories/pastel.jpg' },
  { id: 14, name: 'Frango com Catupiry', price: 11.00, availability: 1, category: 'Pastel', imageUrl: '/images/categories/pastel.jpg' },
  { id: 15, name: 'Chocolate com Banana', price: 10.00, availability: 1, category: 'Pastel', imageUrl: '/images/categories/pastel.jpg' },
  { id: 16, name: 'Batata Frita', price: 18.90, availability: 1, category: 'Porcoes', imageUrl: '/images/categories/snacks.jpg' },
  { id: 17, name: 'Batata com Cheddar e Bacon', price: 25.90, availability: 1, category: 'Porcoes', imageUrl: '/images/categories/batata_bac_chedd.jpg' },
  { id: 18, name: 'Frango à Passarinho', price: 32.90, availability: 1, category: 'Porcoes', imageUrl: '/images/categories/frango.jpg' },
  { id: 19, name: 'Anéis de Cebola', price: 21.90, availability: 1, category: 'Porcoes', imageUrl: '/images/categories/onion_rings.jpg' },
  { id: 21, name: 'Refrigerante Lata', price: 6.00, availability: 1, category: 'Bebidas', imageUrl: '/images/categories/cokel.jpg' },
  { id: 22, name: 'Refrigerante 1L', price: 9.00, availability: 1, category: 'Bebidas', imageUrl: '/images/categories/coke.jpg' },
  { id: 23, name: 'Suco Natural', price: 8.00, availability: 1, category: 'Bebidas', imageUrl: '/images/categories/drinks.jpg' },
  { id: 24, name: 'Água Mineral', price: 4.00, availability: 1, category: 'Bebidas', imageUrl: '/images/categories/water.jpg' },
  { id: 25, name: 'Chopp Pilsen', price: 10.00, availability: 1, category: 'Bebidas', imageUrl: '/images/categories/chopp.jpg' },
  { id: 26, name: 'Cerveja Long Neck', price: 12.00, availability: 1, category: 'Bebidas', imageUrl: '/images/categories/beer.jpg' },
  { id: 28, name: 'Brownie com Sorvete', price: 16.90, availability: 1, category: 'Sobremesa', imageUrl: '/images/categories/brownie.jpg' },
  { id: 29, name: 'Açaí na Tigela', price: 14.90, availability: 1, category: 'Sobremesa', imageUrl: '/images/categories/desserts.jpg' },
  { id: 30, name: 'Milkshake', price: 12.90, availability: 1, category: 'Sobremesa', imageUrl: '/images/categories/milkshake.jpg' },
  { id: 31, name: 'Pudim da Casa', price: 10.90, availability: 1, category: 'Sobremesa', imageUrl: '/images/categories/pudim.jpg' },
];